---
- name: Install Microsft Edge from an exe held on local server
  hosts: all 
 
  collections:
    - ansible.windows
  tasks:
    - name: Create a local directory
      win_file:
        path: C:\temp
        state: directory
        
    - name: Map I drive to installers area
        win_mapped_drive:
          letter: I
          path: \\DC.PETELAB.LOCAL\installers
          state: absent
      

#   - name: Download the MS Edge installer
#     win_shell: 'copy I:\MicrosoftEdgeSetup.exe c:\temp'

    - name: Install MS Edge from c:\temp executable
      win_shell: 'I:\MicrosoftEdgeSetup.exe /silent /install'
