---
- name: Install Microsft Edge from an exe held on local server
  hosts: all 
 
  collections:
    - ansible.windows
  tasks:
    - name: Create a local directory
      win_file:
        path: C:\temp
        state: directory
    
    - name: robocopy    
      win_robocopy:
          src: \\DC.PETELAB.LOCAL\installers
          dest: C:\temp
          flags: * /E /PURGE /XD SOME_DIR /XF SOME_FILE /MT:32

    - name: Install MS Edge from mapped drive executable
      win_shell: 'C:\temp\MicrosoftEdgeSetup.exe /silent /install'
