---
- name: win_file module demo
- hosts: all
  collections:
    - ansible.windows
  vars:
    mydir: 'C:\temp'
  tasks:
    - name: Create a directory
      win_file:
        path: "{{ mydir }}"
        state: directory
