---
- name: win_file copy installer from DC Share
  hosts: all
  collections:
    - ansible.windows
  tasks:
    - name: Create a local directory
      win_file:
        path: C:\temp
        state: directory
    
    - name: Copy file locally    
      win_copy:
        src: '\\DC.PETELAB.LOCAL\installers\NP.exe'
        dest: 'c:\NP.exe'
        remote_src: True
        become: True
        become_method: runas
        become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      vars:
        ansible_become_user: PETELAB\plambie-admin
        ansible_become_pass: DCP4ssword
