---
- name: Notepad++ installation Playbook
  hosts: all
  tasks:
   - name: Installing Notepad++
     win_package:
       path: '\\dc.PETELAB.LOCAL\installers\NP.exe'
       arguments: '/S'
       product_id: 'Notepad++'
       creates_version: '8.7.4'
       creates_path: 'C:\Program Files\Notepad++\notepad++.exe'
       state: present
     when: ansible_os_family == 'Windows'
