- name: install notepad++

  hosts: all
  win_package:
    path: 'etc/ansible/installers/npp.8.4.7.Installer.exe'

    creates_path: 'C:\Program Files (x86)\Notepad++\'
    state: present 
    arguments: /passive /nocontentupdate
