---
- name: Install Notepad from an exe 
  hosts: all 
 
  collections:
    - ansible.windows
  tasks:
    - name: Create a local directory
      win_file:
        path: C:\temp
        state: directory

    - name: Download the Apache installer
      win_get_url:
        url: 'https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.9/npp.8.4.9.Installer.x64.exe'
        dest: 'C:\temp\npp.8.4.9.Installer.x64.exe'

    - name: Install notepad++ executable
      win_shell: "C:\temp\npp.8.4.9.Installer.x64.exe /S"
    
